### ISSUE TITLE
Derive should support "optional" labels/spans

### ISSUE THREAD

**Issue by Techcable** [zkat/miette#110]
I want to wrap [`toml::de::Error`](https://docs.rs/toml/0.5.8/toml/de/struct.Error.html) inside a `Diagnostic` type while still preserving span information.

The `toml::de::Error` type returns an `Option<(usize, usize)>` for its [`line_col` method](https://docs.rs/toml/0.5.8/toml/de/struct.Error.html#method.line_col).

It's unclear how I would integrate this into an automatically derived Diagnostic 😦 

Presumably, wrapping libraries with similar "optional" span information is common.....

**Comment by zkat** [comment]
You're right that derive doesn't support this use-case, although this is definitely more involved than just "forwarding" a method.

The way I've been dealing with this is by [defining a regular Diagnostic that uses `(offset, length)`](https://github.com/zkat/turron/blob/main/crates/nuget-api/src/errors.rs#L87-L101) and then [adding a method to the error type](https://github.com/zkat/turron/blob/main/crates/nuget-api/src/errors.rs#L134-L152).

You then just [`.map_err()`](https://github.com/zkat/turron/blob/main/crates/nuget-api/src/v3/registration.rs#L34-L35) in-situ, as needed.

**Comment by zkat** [comment]
as an aside, I do think this approach is my preferred one, because a lot of these libraries have different encodings for their locations, and miette specifically uses byte offset + length. So in your instance you definitely need to have some kind of conversion in the way.

It might be cool to have something in the macro that lets you specify a conversion method for this, though, so I'll leave this open for other questions and for any passersby who might be inclined to write that bit of macrology :)

**Comment by Techcable** [comment]
Yeah. I'm totally fine with doing `map_err` to do conversions. My problem is when libraries return an `Option<Span>`.

This would effectively require defining two `BadToml` variants, one with a Span and `#[label = "here"]`, and another one without a Span/label :(

What would be nice is `#[label(optional, msg = "...")]` for explicit support for optional labels.
