### ISSUE TITLE
Using miette in a middleware trait definition

### ISSUE THREAD

**Issue by TheNeikos** [zkat/miette#156]
I currently have a trait akin to:

```rust
trait Middleware {
  fn handle(&self) -> Result<(), miette::Error>;
}
```

Which works fine until I try to use that `Error` in my own error reporting. I hit a couple of snags which I am not sure how to resolve:

1. `Error` does not implement `Diagnostic` or `std::error::Error`, meaning that I can't use it in `#[related]` _nor_ in `thiserror::Error` `#[source]` annotations. I _could_ implement `Diagnostic` myself, but this is particularly 'annoying' in my case since its a enum with a dozen of error kinds.
2. `#[related]` wants to see something that is `IntoIterator` but I usually just have a single error on which I want to add context. My current 'workaround' is to use a single element array, but it does look weird haha.

Now, these are just some painpoints I identified in this situation. I don't know if/how they come from my usage of the crate, but I still wanted to report my experience and potentially discuss solutions/changes that would make it easier to use here.

Thank you for making the crate!

**Comment by zkat** [comment]
1. This is correct, and intentional, because of How Type Stuff Works. Once you enter `miette::Error` (aka `miette::Report`) land, you can only downcast to specific errors. If you need to do this kind of thing, I suggest using a wrapper Diagnostic enum instead of `miette::Error`.
2. I have feelings about `#[related]`. I think the API could be much better, and there's been some discussion over at https://github.com/zkat/miette/issues/139#issuecomment-1074561741, but nothing specific has come up as of yet.

Thanks for the comments, and I'm glad you're enjoying the crate! Stuff like this is super welcome :)

**Comment by TheNeikos** [comment]
I've been thinking about your response @zkat, could you explain what you mean with a 'wrapper diagnostic enum'? I currently can't picture the problem.

I've also tried to use a `Box<dyn Diagnostic>` but I still can't use it as a `source()` since trait upcasting is still unstable in Rust :c

**Comment by zkat** [comment]
[`http-types` has an interesting solution for this](https://github.com/http-rs/http-types/pull/395/), for the sake of handling the same scenario (dealing with dynamic errors in middleware).

I don't know what the ideal solution here is. I admit it's hard and I don't have a good answer, but I think the above is a good direction to try and head in and see how it feels.

**Comment by TheNeikos** [comment]
I'd say that with the merging of #165 most of the pain points are gone and should work fine until the Provider API is there in some form. Thanks!
