### ISSUE TITLE
SourceCode on Option<impl SourceCode>? 

### ISSUE THREAD

**Issue by mimoo** [zkat/miette#217]
I would find it useful if there were such an implementation:

```rust
impl miette::SourceCode for Option<NamedSource> {
    fn read_span<'a>(
        &'a self,
        span: &miette::SourceSpan,
        context_lines_before: usize,
        context_lines_after: usize,
    ) -> std::result::Result<Box<dyn miette::SpanContents<'a> + 'a>, miette::MietteError> {
        self.expect("no source code was set in the error").read_span(span, context_lines_before, context_lines_after)     
    }
}
```

or perhaps a more general implementation:

```rust
impl<T> miette::SourceCode for Option<T> where T: miette::SourceCode {
    fn read_span<'a>(
        &'a self,
        span: &miette::SourceSpan,
        context_lines_before: usize,
        context_lines_after: usize,
    ) -> std::result::Result<Box<dyn miette::SpanContents<'a> + 'a>, miette::MietteError> {
        self.expect("no source code was set in the error").read_span(span, context_lines_before, context_lines_after)     
    }
}
```

this way I can have an optional source up until I set it:

```rust
#[source_code]
src: Option<NamedSource>
```

BTW I also noticed that I can't call this field `source` otherwise I get a weird error. Might be good to have a better error when I call the field `source` instead of `src`

**Comment by Benjamin-L** [comment]
Having an implementation for `Option<T: SourceCode>` that panics at runtime when it's `None` is not ideal, since it makes it easy to accidentally cause a panic when trying to print an error. I think there's a better option though. The [`Diagnostic::source_code`](https://docs.rs/miette/latest/miette/trait.Diagnostic.html#method.source_code) method returns `Option<&dyn SourceCode>`. Currently the `Diagnostic` derive macro always returns `Some(src)` when a field is annotated with `#[source_code]`, and always returns `None` otherwise. We could update it to pass `src` through as an `Option` when applicable, which should handle your use-case.

**Comment by kallisti-dev** [comment]
Just wanted to say that I would also find this very useful on `#[diagnostic_source]` as well, to optionally provide more detailed debugging info based on environment variables, cli options, configuration, etc. This could also use a similar implementation to what @Benjamin-L suggested for `#[source_code]`

**Comment by zkat** [comment]
this might be a nice thing to have, yes.

And regarding calling the field `source`: this is because `thiserror` uses that field name to determine its own source. It's not a miette thing.
