### ISSUE TITLE
`SourceSpan` from `LineColumn`?

### ISSUE THREAD

**Issue by blyxyas** [zkat/miette#231]
Hi, I'm trying to convert from [`proc_macro2::LineColumn`](https://docs.rs/proc-macro2/latest/proc_macro2/struct.LineColumn.html) to a `SourceSpan`.

Is there a way to do this? `proc_macro2::LineColumn` is the struct that uses syn to store the start and end of a `Span`, I've been trying doing  things for ~2 days. Does someone have the solution? Or maybe implementing a new method, since `syn` is the most downloaded crate?

**Comment by zkat** [comment]
Two notes:

For one, what you're able to convert to is from `LineColumn` to [`SourceOffset`](https://github.com/zkat/miette/blob/main/src/protocol.rs#L441), since a `LineColumn` is a single-point specifier, not a span (that would be a [`proc_macro2::Span`](https://docs.rs/proc-macro2/latest/proc_macro2/struct.Span.html).

For two, this is a very easy conversion, but _you must have the source text_, because you need to keep a running tab of newlines that you've run into, and reset counters accordingly. Or, if you want to make it even easier, you can just use a utility included right in miette: [`SourceOffset::from_location`](https://github.com/zkat/miette/blob/main/src/protocol.rs#L441), which takes the text, a line, a column, and gives you back a `SourceOffset`. You can then turn this into a zero-length `SourceSpan` by just using `.into()`, which will give you a zero-length `SourceSpan`. Up to you and whatever your needs are.

Does this help?

**Comment by blyxyas** [comment]
Yes! It works.

---

If anyone in the future is reading this with the same problem, you can use this function:

```rust
pub fn get_span(src: &str, start: &LineColumn, end: &LineColumn) -> SourceSpan {
    let mut remaining_lines = end.line - 1;
    let mut bytepos_start: usize = 0;
    let mut bytepos_end: usize = 0;
	for (i, c) in src.chars().enumerate() {
        if c == '\n' {
			remaining_lines -= 1;
			if end.line - remaining_lines == start.line {
				bytepos_start = i + start.column + 1;
			} else {
				bytepos_end = i + end.column;
			}
        }
    }
    return (bytepos_start..bytepos_end).into();
}
```

This worked for me.
