### ISSUE TITLE
`Report::with_source_code` overrides already provided source code 

### ISSUE THREAD

**Issue by gavrilikhin-d** [zkat/miette#299]
While working on compiler, I stumbled upon a panic from formatter. 
Turns out, using `with_source_code` overrides **EVERY** source codes, even already provided.

This is undesirable in multi-source environments. By intuition, `with_source_code` should only replace missing (not provided) source codes.

Here is a small example.
```rs
#[test]
fn miette_two_source_codes() -> miette::Result<()> {
    #[derive(thiserror::Error, miette::Diagnostic, Debug, Clone, PartialEq)]
    #[error("error")]
    struct E {
        #[label("here")]
        at: miette::SourceSpan,
        #[source_code]
        source_code: String,
    };

    let source1 = "abcdef";
    let source2 = "a";
    Err(miette::Report::from(E {
        at: (4..5).into(),
        source_code: source1.to_string(),
    })
    .with_source_code(source2.to_string()))
}
```

**Comment by kallisti-dev** [comment]
I'm not convinced this is the intuitive behavior. I would expect `with_source_code` to override any existing source code that was given prior, via the derive macro or otherwise. I think it would be more confusing for the user if `with_source_code` *didn't* override the source code, and it would make it impossible to use this feature in cases where you do want to override it.

The code to avoid overriding would look something like this:

```rust
// create report with source1
let report = Err(miette::Report::from(E {
    at: (4..5).into(),
    source_code: source1.to_string(),
}));
// shadow previous variable (or you can use mut instead)
let report = match report.source_code() {
    None => report.with_source_code(source2.to_string()),
    _ => report
}
```
I think this makes the behavior more explicit to the reader, whereas `with_source_code` implicitly and silently ignoring the provided source code would be surprising to someone who was looking to override it.

Maybe a separate helper method for this behavior would be better? It could be named to make it clear that it's only adding source code if missing.

**Comment by kallisti-dev** [comment]
I'm not convinced this is the intuitive behavior. I would expect `with_source_code` to override any existing source code that was given prior, via the derive macro or otherwise. I think it would be more confusing for the user if `with_source_code` *didn't* override the source code, and it would make it impossible to use this feature in cases where you do want to override it.

I'm also not sure how this could be implemented, due to the type erasure of boxing the Diagnostic. You could downcast, but you would need to know the specific concrete type, not just "some type that implements Diagnostic".

Maybe a separate helper method for this behavior would be better? Assuming there's some way to fetch the existing source code (which I'm not sure there is currently). It could be named to make it clear that it's only adding source code if missing.

**Comment by gavrilikhin-d** [comment]
> I'm not convinced this is the intuitive behavior. 
> I would expect with_source_code to override any existing source code 

It's hard to name a single use-case for changing source code without changing any locations for me.

**Comment by gavrilikhin-d** [comment]
Here is a real-life example when I need non-overriding `Report::with_source_code`:

1. There is a `TypeMismatch` error for passing arguments of incorrect type to function
```rs
/// Diagnostic for not convertible types
#[derive(Error, Debug, Clone, PartialEq)]
#[error("expected `{expected}` type, got `{got}`")]
pub struct TypeMismatch {
    /// Expected type
    pub expected: TypeWithSpan,
    /// Real type
    pub got: TypeWithSpan,
}

impl Diagnostic for TypeMismatch {
    fn code<'a>(&'a self) -> Option<Box<dyn Display + 'a>> {
        Some(Box::new("semantics::type_mismatch"))
    }

    fn related<'a>(&'a self) -> Option<Box<dyn Iterator<Item = &'a dyn Diagnostic> + 'a>> {
        Some(Box::new(
            vec![
                &self.expected as &dyn Diagnostic,
                &self.got as &dyn Diagnostic,
            ]
            .into_iter(),
        ))
    }
}
```

2.  `TypeWithSpan` stores a `SourceFile` or `None`, if it's located in the current file.
```rs
#[derive(Error, Diagnostic, Debug, Clone, PartialEq)]
#[error("{ty}")]
pub struct TypeWithSpan {
    /// Type to show
    pub ty: Type,

    /// Span of the thing with the type
    #[label("this has `{ty}` type")]
    pub at: SourceSpan,

    /// Source code of the module, this type is located at
    #[source_code]
    pub source_file: Option<SourceFile>,
}

impl From<TypeWithSpan> for SourceSpan {
    fn from(value: TypeWithSpan) -> Self {
        value.at
    }
}
```
