### ISSUE TITLE
New Crates.io Release?

### ISSUE THREAD

**Issue by TheLostLambda** [zkat/miette#332]
It seems like a number of improvements and fixes and been merged since last July (which I think is when 5.10.0 was released), and I figured it would be nice to have those bundled into a new version on crates.io!

I don't know if there was a particular milestone that was blocking the next version, but if not, it could be lovely to have an update so I can replace my git dependencies!

Thanks a ton,
Brooks

**Comment by zkat** [comment]
I've definitely had written down that I need to tag a new miette, but I want to be more intentional about this release and possibly include some breaking changes into a 6.0 release (I think there's already breaking changes merged in?)

The reason it hasn't happened yet is because I had a baby last April and time kinda flew away. So I'm just trying to find time+motivation to sit down and do this. Sorry for the wait.

**Comment by TheLostLambda** [comment]
Hi Kat!

No worries at all! I reckon baby humans might be slightly higher on the priority list than crates.io releases!

Thanks a ton for the update and hope you're well :)

**Comment by zkat** [comment]
6.0.0!(and 6.0.1! 😅) is out now, with all the patches from the past however long! Thanks everyone for your patience. I finally managed to snag some time and spoons :)
