### ISSUE TITLE
Feature request: output an error as `json::Value` or `serde_json::Value` directly

### ISSUE THREAD

**Issue by cdisselkoen** [zkat/miette#360]
`miette` has a `JSONReportHandler` which allows you to print errors as JSON.  However, that results in writing text-format JSON to a `fmt::Write`r, and if you want the JSON as a `json::Value` or `serde_json::Value`, you have to re-parse the string AFAICT.  (If I'm missing something or misunderstanding something, I apologize and please correct me :) )  

It would be great if `miette` had a function for outputting an error directly as `json::Value` or `serde_json::Value`.

**Comment by zkat** [comment]
miette does not have a dependency on `serde_json` or similar, and I think it should be up to end users to determine which `Value` type they want to use. As such, I don't think it's appropriate for miette itself to pull in a dependency like this, when it's trivial to do the parsing yourself. The cost of parsing the string will almost definitely be trivial, because in 99% of cases, displayed errors are relatively low-frequency things (since they're intended for human consumption).

As such, I'm inclined to decline this feature request. I just don't think the cost is worth the benefit.

**Comment by cdisselkoen** [comment]
That's reasonable.  I'll close this.
